#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-uuidtools
Version  : 2.1.5
Release  : 1
URL      : https://rubygems.org/downloads/uuidtools-2.1.5.gem
Source0  : https://rubygems.org/downloads/uuidtools-2.1.5.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
BuildRequires : ruby
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-launchy
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support
BuildRequires : rubygem-yard

%description
# UUIDTools
<dl>
<dt>Homepage</dt><dd><a href="https://github.com/sporkmonger/uuidtools">sporkmonger/uuidtools</a></dd>
<dt>Author</dt><dd><a href="mailto:bob@sporkmonger.com">Bob Aman</a></dd>
<dt>License</dt><dd>Apache 2.0</dd>
</dl>

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n uuidtools-2.1.5
gem spec %{SOURCE0} -l --ruby > rubygem-uuidtools.gemspec

%build
gem build rubygem-uuidtools.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
uuidtools-2.1.5.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/uuidtools-2.1.5
rspec -I.:lib spec/ || :
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/uuidtools-2.1.5.gem
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/SecureRandom/base64-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/SecureRandom/cdesc-SecureRandom.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/SecureRandom/hex-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/SecureRandom/random_bytes-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/SecureRandom/random_number-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/%3c%3d%3e-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/cdesc-UUID.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/clock_seq_hi_and_reserved-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/clock_seq_low-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/convert_byte_string_to_int-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/convert_int_to_byte_string-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/create_from_hash-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/eql%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/first_mac-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/generate_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/generate_hexdigest-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/generate_i-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/generate_raw-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/generate_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/hexdigest-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/ifconfig-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/ifconfig_command-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/ifconfig_path-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/ifconfig_path_default-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/ip_command-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/ip_path-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/ip_path_default-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/mac_address%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/mac_address-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/mac_address-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/md5_create-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/nil_uuid%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/nodes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/os_class-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/parse-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/parse_hexdigest-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/parse_int-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/parse_raw-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/random_create-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/random_node_id%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/raw-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/sha1_create-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/time_hi_and_version-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/time_low-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/time_mid-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/timestamp-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/timestamp_create-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/to_i-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/to_str-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/to_uri-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/valid%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/variant-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/UUID/version-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/VERSION/cdesc-VERSION.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/UUIDTools/cdesc-UUIDTools.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/uuidtools-2.1.5/ri/page-README_md.ri
/usr/lib64/ruby/gems/2.2.0/gems/uuidtools-2.1.5/CHANGELOG
/usr/lib64/ruby/gems/2.2.0/gems/uuidtools-2.1.5/LICENSE.txt
/usr/lib64/ruby/gems/2.2.0/gems/uuidtools-2.1.5/README.md
/usr/lib64/ruby/gems/2.2.0/gems/uuidtools-2.1.5/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/uuidtools-2.1.5/lib/compat/securerandom.rb
/usr/lib64/ruby/gems/2.2.0/gems/uuidtools-2.1.5/lib/uuidtools.rb
/usr/lib64/ruby/gems/2.2.0/gems/uuidtools-2.1.5/lib/uuidtools/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/uuidtools-2.1.5/spec/spec.opts
/usr/lib64/ruby/gems/2.2.0/gems/uuidtools-2.1.5/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/uuidtools-2.1.5/spec/uuidtools/mac_address_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/uuidtools-2.1.5/spec/uuidtools/utility_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/uuidtools-2.1.5/spec/uuidtools/uuid_creation_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/uuidtools-2.1.5/spec/uuidtools/uuid_parsing_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/uuidtools-2.1.5/tasks/benchmark.rake
/usr/lib64/ruby/gems/2.2.0/gems/uuidtools-2.1.5/tasks/gem.rake
/usr/lib64/ruby/gems/2.2.0/gems/uuidtools-2.1.5/tasks/git.rake
/usr/lib64/ruby/gems/2.2.0/gems/uuidtools-2.1.5/tasks/metrics.rake
/usr/lib64/ruby/gems/2.2.0/gems/uuidtools-2.1.5/tasks/rspec.rake
/usr/lib64/ruby/gems/2.2.0/gems/uuidtools-2.1.5/tasks/yard.rake
/usr/lib64/ruby/gems/2.2.0/gems/uuidtools-2.1.5/website/index.html
/usr/lib64/ruby/gems/2.2.0/specifications/uuidtools-2.1.5.gemspec
